/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ActivityType { 'id' : bigint, 'name' : string }
export interface Environment { 'id' : bigint, 'name' : string }
export type Time = bigint;
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface WorkLogEntry {
  'id' : bigint,
  'date' : string,
  'user' : Principal,
  'environmentIds' : Array<bigint>,
  'notes' : [] | [string],
  'timestamp' : Time,
  'activityTypeId' : bigint,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createActivityType' : ActorMethod<[string], bigint>,
  'createEnvironment' : ActorMethod<[string], bigint>,
  'createWorkLogEntry' : ActorMethod<
    [bigint, Array<bigint>, [] | [string], string],
    bigint
  >,
  'deleteActivityType' : ActorMethod<[bigint], undefined>,
  'deleteEnvironment' : ActorMethod<[bigint], undefined>,
  'deleteWorkLogEntry' : ActorMethod<[bigint], undefined>,
  'getActivityTypeStats' : ActorMethod<
    [Principal, string],
    Array<[bigint, bigint]>
  >,
  'getActivityTypes' : ActorMethod<[], Array<ActivityType>>,
  'getAllTeamWorkLogEntries' : ActorMethod<
    [string, string, [] | [Principal], [] | [bigint]],
    Array<WorkLogEntry>
  >,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getEnvironments' : ActorMethod<[], Array<Environment>>,
  'getMyWorkLogEntries' : ActorMethod<[string, string], Array<WorkLogEntry>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'updateActivityType' : ActorMethod<[bigint, string], undefined>,
  'updateEnvironment' : ActorMethod<[bigint, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];