/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ActivityType = IDL.Record({ 'id' : IDL.Int, 'name' : IDL.Text });
export const Time = IDL.Int;
export const WorkLogEntry = IDL.Record({
  'id' : IDL.Int,
  'date' : IDL.Text,
  'user' : IDL.Principal,
  'environmentIds' : IDL.Vec(IDL.Int),
  'notes' : IDL.Opt(IDL.Text),
  'timestamp' : Time,
  'activityTypeId' : IDL.Int,
});
export const Environment = IDL.Record({ 'id' : IDL.Int, 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createActivityType' : IDL.Func([IDL.Text], [IDL.Int], []),
  'createEnvironment' : IDL.Func([IDL.Text], [IDL.Int], []),
  'createWorkLogEntry' : IDL.Func(
      [IDL.Int, IDL.Vec(IDL.Int), IDL.Opt(IDL.Text), IDL.Text],
      [IDL.Int],
      [],
    ),
  'deleteActivityType' : IDL.Func([IDL.Int], [], []),
  'deleteEnvironment' : IDL.Func([IDL.Int], [], []),
  'deleteWorkLogEntry' : IDL.Func([IDL.Int], [], []),
  'getActivityTypeStats' : IDL.Func(
      [IDL.Principal, IDL.Text],
      [IDL.Vec(IDL.Tuple(IDL.Int, IDL.Nat))],
      ['query'],
    ),
  'getActivityTypes' : IDL.Func([], [IDL.Vec(ActivityType)], ['query']),
  'getAllTeamWorkLogEntries' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Opt(IDL.Principal), IDL.Opt(IDL.Int)],
      [IDL.Vec(WorkLogEntry)],
      ['query'],
    ),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getEnvironments' : IDL.Func([], [IDL.Vec(Environment)], ['query']),
  'getMyWorkLogEntries' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Vec(WorkLogEntry)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'updateActivityType' : IDL.Func([IDL.Int, IDL.Text], [], []),
  'updateEnvironment' : IDL.Func([IDL.Int, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ActivityType = IDL.Record({ 'id' : IDL.Int, 'name' : IDL.Text });
  const Time = IDL.Int;
  const WorkLogEntry = IDL.Record({
    'id' : IDL.Int,
    'date' : IDL.Text,
    'user' : IDL.Principal,
    'environmentIds' : IDL.Vec(IDL.Int),
    'notes' : IDL.Opt(IDL.Text),
    'timestamp' : Time,
    'activityTypeId' : IDL.Int,
  });
  const Environment = IDL.Record({ 'id' : IDL.Int, 'name' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createActivityType' : IDL.Func([IDL.Text], [IDL.Int], []),
    'createEnvironment' : IDL.Func([IDL.Text], [IDL.Int], []),
    'createWorkLogEntry' : IDL.Func(
        [IDL.Int, IDL.Vec(IDL.Int), IDL.Opt(IDL.Text), IDL.Text],
        [IDL.Int],
        [],
      ),
    'deleteActivityType' : IDL.Func([IDL.Int], [], []),
    'deleteEnvironment' : IDL.Func([IDL.Int], [], []),
    'deleteWorkLogEntry' : IDL.Func([IDL.Int], [], []),
    'getActivityTypeStats' : IDL.Func(
        [IDL.Principal, IDL.Text],
        [IDL.Vec(IDL.Tuple(IDL.Int, IDL.Nat))],
        ['query'],
      ),
    'getActivityTypes' : IDL.Func([], [IDL.Vec(ActivityType)], ['query']),
    'getAllTeamWorkLogEntries' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Opt(IDL.Principal), IDL.Opt(IDL.Int)],
        [IDL.Vec(WorkLogEntry)],
        ['query'],
      ),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getEnvironments' : IDL.Func([], [IDL.Vec(Environment)], ['query']),
    'getMyWorkLogEntries' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Vec(WorkLogEntry)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'updateActivityType' : IDL.Func([IDL.Int, IDL.Text], [], []),
    'updateEnvironment' : IDL.Func([IDL.Int, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };